# https://github.com/marketplace/actions/github-action-for-yarn

name: Run Tests

on:
  push:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: borales/actions-yarn@v3.0.0
        name: Install Dependencies
        with:
            cmd: install
      # - uses: borales/actions-yarn@v3.0.0
      #   name: Lint
      #   with:
      #     cmd: lint # will run `yarn lint` command
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test # will run `yarn test` command
      - uses: borales/actions-yarn@v3.0.0
        name: Build
        with:
          cmd: build # will run `yarn build` command
